data:
  raw_data: "data/raw/enron_spam_data.csv"

  cleaned_y: "data/cleaned/cleaned_y.csv"
  vectorizer: "data/cleaned/vectorizer.joblib"
  X_sparse: "data/cleaned/X_sparse.npz"

  pickle_file: "data/model/model.pkl"

settings:
  clean_data: False
  train_logistic_regression: True
  train_random_forest: False
  train_naive_bayes: False
  save_pickle_file: True
