data:
  raw_data: "data/raw/airlines_flights_data.csv"


model:
  n_estimators: 100 
  target: ["price"] 

  RandomForestRegressor:
    n_estimators: 100
    max_depth: 10

  LinearRegression:
    normalize: False


features:
  non_categorical_features: ['flight','duration','days_left','price','stops']
  numerical_features: ['duration','days_left','stops']
  drop_column: ["flight","index"]

prep:
  test_size: 0.3
  random_state: 42
  target_col: "price"

  ml_models_1: RandomForestRegressor

  


