data:
  raw_data: "data\raw\airlines_flights_data.csv"

model:
  n_estimators: 100

features:
  non_categorical_features: ['flight']                # one-hot
  numerical_features: ['duration', 'days_left', 'stops']
  target: 'price'
